### ISSUE TITLE
Installation of TailwindCSS

### ISSUE THREAD

**Issue by kumbu132** [TechMalawi/techmalawi#15]
adding tailwind boilerplate.

**Comment by joelfickson** [comment]
Awesome, please assign this task to yourself.

**Comment by kumbu132** [comment]
There's no cog next to the assignees section, I need the right permissions to do that.
 
 I should be seeing this ![image](https://user-images.githubusercontent.com/71005514/175890577-0729c56d-7464-48c8-aad3-f03643bf63bf.png)
 
 but instead I am seeing ![image](https://user-images.githubusercontent.com/71005514/175890719-4fcf3355-1ba0-46c9-bc6e-619995f8fe54.png)

**Comment by kumbu132** [comment]
thanks :)

**Comment by joelfickson** [comment]
Got it.

**Comment by joelfickson** [comment]
I think that the installation may have already been done with the initial setup, you can verify.

**Comment by kumbu132** [comment]
Ah yes, it's been resolved in a PR that was just merged
